apiVersion: v1
kind: Service
metadata:
  name: transaction-api-service
  namespace: eastcoders
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8224
    targetPort: 8224
  selector:
      app: banking
      type: api
      tier: backend